# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches-ignore:  main 
  pull_request:
    branches:  "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run:  |
        dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx" mkdir -p TestResults mv **/test_results.trx TestResults/
    - name:  Install Test Report Generator 
      run:  dotnet tool install --global dotnet-reportgenerator-globaltool
    - name:  Generate HTML Report
      run:  |
        reportgenerator \ 
          "-reports:**/test_results.trx" \
          "-targetdir:TestResults/html" \
          -reporttypes:Html

    - name:  Upload Test Results 
      uses:  actions/upload-artifacts@v4
      with:
        name:  dotnet-test-reports
        path:  TestResults/
    
   
